services:
  - type: web
    name: playwright-extractor
    env: node
    plan: free
    buildCommand: |
      npm install
      npx playwright install
    startCommand: npm start
    envVars:
      - key: PORT
        value: "10000"
